// 지역별 드라마 촬영지 및 관광지 데이터

export function getRegionLocations(region: string, dramaTheme: 'heartwarming' | 'game-food', isKorean: boolean) {
  const data: Record<string, Record<string, any[]>> = {
    seoul: {
      heartwarming: [
        {
          name: isKorean ? '북촌 한옥마을' : 'Bukchon Hanok Village',
          address: isKorean ? '종로구, 서울' : 'Jongno-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '전통 문화' : 'Traditional Culture',
          description: isKorean ? '전통 한옥에서 따뜻한 인심을 느끼며 현지 가족과 교류하세요.' : 'Feel warm hospitality in traditional hanok and connect with local families.',
          dramaScene: isKorean ? '주민들과 차를 나누며 진심 어린 대화를 나누는 골목길 장면' : 'Alley scenes where neighbors share tea and heartfelt conversations',
          regionalExperience: isKorean ? '🏡 한옥 체험: 가족 운영 게스트하우스 방문, 전통 찻집에서 이야기 나누기, 현지 장인 만나기' : '🏡 Hanok Experience: Visit family-run guesthouses, share stories at tea houses, meet local artisans',
          whyRecommended: isKorean
            ? '드라마 속 따뜻한 인정을 직접 경험할 수 있는 곳이에요. 600년 역사를 지닌 한옥에서 실제로 주민들이 생활하고 있어, 관광지가 아닌 살아있는 공동체의 모습을 볼 수 있습니다. 특히 아침 일찍 방문하면 주민들이 골목을 쓸고 인사를 나누는 모습에서 진짜 서울 사람들의 따뜻한 일상을 느낄 수 있어요.'
            : 'Experience the heartwarming connections from the drama in real life. In these 600-year-old hanok where residents actually live, you\'ll see a living community, not just a tourist spot. Visit early morning to see residents sweeping alleys and greeting each other - feel the warm daily life of real Seoulites.',
          coordinates: { lat: 37.5826, lng: 126.9831 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 3호선 안국역' : '🚇 Anguk Station (Line 3)',
          dayNumber: 1,
          timeSlot: isKorean ? '오전 9:00-12:00' : '9:00 AM - 12:00 PM',
        },
        {
          name: isKorean ? '통인시장 (도시락 카페)' : 'Tongin Market (Lunchbox Cafe)',
          address: isKorean ? '종로구, 서울' : 'Jongno-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '전통 시장' : 'Traditional Market',
          description: isKorean ? '시장 상인들과 소통하며 직접 도시락을 만들어보세요.' : 'Interact with market vendors and create your own lunchbox.',
          dramaScene: isKorean ? '시장 아주머니들의 따뜻한 정을 느끼는 장면' : 'Scenes feeling the warmth of market ajummas',
          regionalExperience: isKorean ? '🍱 시장 체험: 엽전으로 장보기, 상인들과 대화, 손님처럼이 아닌 이웃처럼' : '🍱 Market Experience: Shop with old coins, chat with vendors, feel like a neighbor',
          whyRecommended: isKorean
            ? '옛날 엽전으로 장을 보는 독특한 경험! 시장 상인 아주머니들이 정말 친절하게 음식 하나하나 설명해주시고, 맛보라고 권하시는 모습에서 진짜 한국의 정을 느낄 수 있어요. 점심때 방문해서 직접 도시락을 꾸려먹으면 서울 로컬의 일상을 경험하는 것 같은 기분이 들어요.'
            : 'Unique experience shopping with old coins! Market ajummas kindly explain each dish and offer tastings - you\'ll feel genuine Korean warmth. Visit at lunchtime to pack your own lunchbox and experience Seoul locals\' daily life.',
          coordinates: { lat: 37.5759, lng: 126.9689 },
          travelTime: isKorean ? '도보 15분' : '15 min walk',
          transportInfo: isKorean ? '🚶 북촌에서 도보' : '🚶 Walk from Bukchon',
          dayNumber: 1,
          timeSlot: isKorean ? '오후 12:00-14:00' : '12:00 PM - 2:00 PM',
        },
        {
          name: isKorean ? '익선동 한옥 거리' : 'Ikseon-dong Hanok Street',
          address: isKorean ? '종로구, 서울' : 'Jongno-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '로컬 카페' : 'Local Cafes',
          description: isKorean ? '젊은 창업가들이 운영하는 한옥 카페에서 그들의 이야기를 들어보세요.' : 'Hear stories from young entrepreneurs running hanok cafes.',
          dramaScene: isKorean ? '전통과 현대가 만나 새로운 꿈을 키우는 청년들의 모습' : 'Young people nurturing dreams where tradition meets modernity',
          regionalExperience: isKorean ? '☕ 카페 투어: 한옥 카페 주인과 대화, 수제 디저트, 작은 골목의 정취' : '☕ Cafe Tour: Chat with hanok cafe owners, handmade desserts, small alley charm',
          coordinates: { lat: 37.5717, lng: 126.9905 },
          travelTime: isKorean ? '지하철 10분' : '10 min by metro',
          transportInfo: isKorean ? '🚇 3호선 종로3가역' : '🚇 Jongno 3-ga Station (Line 3)',
        },
      ],
      'game-food': [
        {
          name: isKorean ? '동대문디자인플라자 (DDP)' : 'Dongdaemun Design Plaza (DDP)',
          address: isKorean ? '중구, 서울' : 'Jung-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '현대 서울' : 'Modern Seoul',
          description: isKorean ? '현대 한국을 대표하는 미래지향적 건축물, 주변 24시간 쇼핑가.' : 'Futuristic architecture representing modern Korea, surrounded by 24-hour shopping.',
          dramaScene: isKorean ? '서울의 현대 건축을 보여주는 VIP 라운지 장면' : 'VIP lounge scenes showcasing Seoul\'s contemporary architecture',
          regionalExperience: isKorean ? '🌆 동대문: 야시장 먹거리, 패션 도매시장, 24시간 쇼핑 투어' : '🌆 Dongdaemun: Night market food, fashion wholesale, 24-hour shopping tour',
          coordinates: { lat: 37.5665, lng: 127.0095 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 2/4/5호선 동대문역사문화공원역' : '🚇 Line 2/4/5 DDP Station',
        },
        {
          name: isKorean ? '광장시장' : 'Gwangjang Market',
          address: isKorean ? '종로구, 서울' : 'Jongno-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '길거리 음식' : 'Street Food',
          description: isKorean ? '마약김밥, 빈대떡, 육회 등 전통 길거리 음식의 천국.' : 'Heaven of traditional street food - gimbap, bindaetteok, yukhoe.',
          dramaScene: isKorean ? '서민들의 애환이 담긴 전통 시장, 달고나를 파는 할머니' : 'Traditional market showing common people\'s lives, grandma selling dalgona',
          regionalExperience: isKorean ? '🍜 먹자골목: 빈대떡 만들기 보기, 마약김밥 맛보기, 막걸리 한잔' : '🍜 Food Alley: Watch bindaetteok making, taste famous gimbap, makgeolli drink',
          coordinates: { lat: 37.5701, lng: 126.9996 },
          travelTime: isKorean ? '지하철 15분' : '15 min by metro',
          transportInfo: isKorean ? '🚇 1호선 종로5가역' : '🚇 Jongno 5-ga Station (Line 1)',
        },
        {
          name: isKorean ? '성수동 놀이터 & 카페거리' : 'Seongsu-dong Playground & Cafe Street',
          address: isKorean ? '성동구, 서울' : 'Seongdong-gu, Seoul',
          region: isKorean ? '서울' : 'Seoul',
          tag: isKorean ? '레트로 게임' : 'Retro Games',
          description: isKorean ? '어린 시절 놀이터와 레트로 감성 카페가 가득한 빈티지 동네.' : 'Vintage neighborhood full of childhood playgrounds and retro cafes.',
          dramaScene: isKorean ? '향수 어린 한국 동네 분위기, 달고나 게임의 배경' : 'Nostalgic Korean neighborhood atmosphere, dalgona game background',
          regionalExperience: isKorean ? '🎮 레트로 체험: 옛날 놀이터, 달고나 만들기 체험, 빈티지 카페 투어' : '🎮 Retro Experience: Old playgrounds, dalgona making, vintage cafe tour',
          coordinates: { lat: 37.5443, lng: 127.0557 },
          travelTime: isKorean ? '지하철 20분' : '20 min by metro',
          transportInfo: isKorean ? '🚇 2호선 성수역' : '🚇 Seongsu Station (Line 2)',
        },
      ],
    },
    jeju: {
      heartwarming: [
        {
          name: isKorean ? '제주 귤 농장 (가족 농장)' : 'Jeju Tangerine Farm (Family Farm)',
          address: isKorean ? '서귀포시, 제주도' : 'Seogwipo, Jeju Island',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '대표 촬영지' : 'Main Filming Location',
          description: isKorean ? '3대째 이어오는 가족 농장에서 귤 수확을 도우며 섬사람들의 따뜻한 정을 느껴보세요.' : 'Help harvest tangerines at a 3-generation family farm and feel the warmth of island people.',
          dramaScene: isKorean ? '등장인물들이 섬 생활의 소박한 즐거움을 발견하는 황금빛 귤밭' : 'Golden tangerine groves where characters discover simple island life joys',
          regionalExperience: isKorean ? '🍊 농장 체험: 농장 가족과 함께 일하기, 전통 간식 나누기, 섬 이야기 듣기' : '🍊 Farm Experience: Work with farming family, share traditional snacks, hear island stories',
          whyRecommended: isKorean
            ? '제주도에서만 경험할 수 있는 특별한 귤 농장 체험! 농장 할머니, 할아버지가 직접 키운 귤을 따면서 제주 사투리로 옛날 이야기를 들을 수 있어요. 관광 농장이 아니라 실제로 3대째 농사짓는 가족 농장이라, 진짜 제주 사람들의 삶을 엿볼 수 있습니다. 수확철(10-1월)에 방문하면 황금빛 귤밭이 정말 장관이에요!'
            : 'Special tangerine farm experience only in Jeju! Pick tangerines with farming grandparents while listening to old stories in Jeju dialect. Not a tourist farm but a real 3-generation family farm - peek into authentic Jeju life. Visit during harvest season (Oct-Jan) for spectacular golden groves!',
          coordinates: { lat: 33.2541, lng: 126.5601 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚗 제주공항에서 30분' : '🚗 30 min from Jeju Airport',
          dayNumber: 1,
          timeSlot: isKorean ? '오전 9:00-12:00' : '9:00 AM - 12:00 PM',
        },
        {
          name: isKorean ? '성산포 해녀의 집' : 'Seongsan Haenyeo House',
          address: isKorean ? '성산읍, 서귀포시, 제주도' : 'Seongsan-eup, Seogwipo, Jeju',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '해녀 문화' : 'Haenyeo Culture',
          description: isKorean ? '해녀 할머니들과 함께 시간을 보내며 제주 여성들의 삶과 지혜를 배워보세요.' : 'Spend time with haenyeo grandmas and learn about Jeju women\'s lives and wisdom.',
          dramaScene: isKorean ? '바다와 함께 살아온 해녀들의 끈끈한 공동체 정신' : 'Strong community spirit of haenyeo who lived with the sea',
          regionalExperience: isKorean ? '🌊 해녀 체험: 해녀 할머니 이야기 듣기, 갓 잡은 해산물 나눠먹기, 물질 문화 배우기' : '🌊 Haenyeo Experience: Listen to grandmas\' stories, share fresh seafood, learn diving culture',
          coordinates: { lat: 33.4589, lng: 126.9426 },
          travelTime: isKorean ? '차로 45분' : '45 min drive',
          transportInfo: isKorean ? '🚗 귤농장에서 40km' : '🚗 40km from farm',
        },
        {
          name: isKorean ? '성읍민속마을 (전통 가옥 스테이)' : 'Seongeup Folk Village (Traditional Home Stay)',
          address: isKorean ? '표선면, 서귀포시, 제주도' : 'Pyoseon-myeon, Seogwipo, Jeju',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '민박 체험' : 'Home Stay',
          description: isKorean ? '전통 초가집에서 하룻밤 머물며 제주 할머니의 손맛을 느껴보세요.' : 'Stay overnight in traditional thatched house and taste Jeju grandma\'s home cooking.',
          dramaScene: isKorean ? '따뜻한 초가집에서 가족처럼 모여 식사하는 장면' : 'Scenes gathering like family for meals in warm thatched houses',
          regionalExperience: isKorean ? '🏡 민박 체험: 제주 할머니 집밥, 돌하르방 이야기, 마을 어르신들과 교류' : '🏡 Home Stay: Grandma\'s home cooking, dol hareubang stories, meet village elders',
          coordinates: { lat: 33.3949, lng: 126.7967 },
          travelTime: isKorean ? '차로 25분' : '25 min drive',
          transportInfo: isKorean ? '🚗 성산에서 18km' : '🚗 18km from Seongsan',
        },
      ],
      'game-food': [
        {
          name: isKorean ? '제주 동문시장' : 'Jeju Dongmun Market',
          address: isKorean ? '제주시, 제주도' : 'Jeju City, Jeju Island',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '전통 시장' : 'Traditional Market',
          description: isKorean ? '제주 최대 전통시장에서 길거리 음식과 해산물을 맛보세요.' : 'Taste street food and seafood at Jeju\'s largest traditional market.',
          dramaScene: isKorean ? '시장 골목을 누비며 간식을 사먹는 장면' : 'Scenes wandering market alleys buying snacks',
          regionalExperience: isKorean ? '🍢 시장 먹거리: 오메기떡, 고등어회, 흑돼지 순대, 한라봉 주스' : '🍢 Market Food: Omegi-tteok, mackerel sashimi, black pork sundae, hallabong juice',
          coordinates: { lat: 33.5138, lng: 126.5277 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚗 제주공항에서 15분' : '🚗 15 min from Jeju Airport',
        },
        {
          name: isKorean ? '제주 흑돼지 거리' : 'Jeju Black Pork Street',
          address: isKorean ? '제주시, 제주도' : 'Jeju City, Jeju Island',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '맛집 거리' : 'Restaurant Street',
          description: isKorean ? '제주 대표 음식인 흑돼지 구이를 맛볼 수 있는 맛집 거리.' : 'Restaurant street where you can taste Jeju\'s signature black pork BBQ.',
          dramaScene: isKorean ? '게임에서 이긴 후 축하 파티 음식 장면' : 'Celebration food scenes after winning games',
          regionalExperience: isKorean ? '🥓 흑돼지 투어: 숯불 구이, 제주 소주, 현지인 맛집 탐방' : '🥓 Black Pork Tour: Charcoal BBQ, Jeju soju, local favorite restaurants',
          coordinates: { lat: 33.4890, lng: 126.4983 },
          travelTime: isKorean ? '차로 20분' : '20 min drive',
          transportInfo: isKorean ? '🚗 시내버스 이용 가능' : '🚗 City bus available',
        },
        {
          name: isKorean ? '협재 해변 & 카페 거리' : 'Hyeopjae Beach & Cafe Street',
          address: isKorean ? '한림읍, 제주시' : 'Hallim-eup, Jeju City',
          region: isKorean ? '제주도' : 'Jeju Island',
          tag: isKorean ? '해변 먹거리' : 'Beach Food',
          description: isKorean ? '에메랄드빛 바다를 보며 즐기는 해변 카페와 간식.' : 'Beach cafes and snacks enjoyed with emerald sea views.',
          dramaScene: isKorean ? '해변에서 게임을 하며 간식을 먹는 여유로운 장면' : 'Leisurely scenes playing games and eating snacks at beach',
          regionalExperience: isKorean ? '🏖️ 해변 투어: 성게알 비빔밥, 오션뷰 카페, 전복죽' : '🏖️ Beach Tour: Sea urchin bibimbap, ocean view cafes, abalone porridge',
          coordinates: { lat: 33.3941, lng: 126.2396 },
          travelTime: isKorean ? '차로 40분' : '40 min drive',
          transportInfo: isKorean ? '🚗 제주시에서 서쪽 해안' : '🚗 West coast from Jeju City',
        },
      ],
    },
    busan: {
      heartwarming: [
        {
          name: isKorean ? '감천문화마을' : 'Gamcheon Culture Village',
          address: isKorean ? '사하구, 부산' : 'Saha-gu, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '예술 마을' : 'Art Village',
          description: isKorean ? '전쟁 피난민들이 만든 마을이 이제는 예술가들과 주민들이 함께 가꾸는 따뜻한 공동체로 변했습니다.' : 'A village built by war refugees transformed into a warm community nurtured by artists and residents.',
          dramaScene: isKorean ? '좁은 골목에서 이웃과 인사를 나누며 서로 돕는 마을 사람들의 모습' : 'Scenes of villagers greeting and helping each other in narrow alleys',
          regionalExperience: isKorean ? '🎨 마을 체험: 벽화 골목 탐방, 주민 카페에서 커피, 마을 해설사와 역사 이야기' : '🎨 Village Experience: Mural alley tour, coffee at resident cafes, history stories with village guides',
          coordinates: { lat: 35.0975, lng: 129.0103 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 1호선 토성역 → 🚌 마을버스' : '🚇 Toseong Station (Line 1) → 🚌 Village bus',
        },
        {
          name: isKorean ? '부산 국제시장 & 깡통시장' : 'Busan International Market & Kkangtong Market',
          address: isKorean ? '중구, 부산' : 'Jung-gu, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '전통 시장' : 'Traditional Market',
          description: isKorean ? '부산 아저씨 아줌마들의 인심 좋은 시장. 시장 상인들과 정담게 대화하며 부산 사투리를 배워보세요.' : 'Market full of kind-hearted Busan ajussi and ajumma. Chat with vendors and learn Busan dialect.',
          dramaScene: isKorean ? '시장 아저씨들이 손님을 가족처럼 챙겨주는 인정 넘치는 장면' : 'Heartwarming scenes of market uncles treating customers like family',
          regionalExperience: isKorean ? '🛍️ 시장 투어: 씨앗호떡 맛보기, 상인 아줌마와 수다, 부산 특산물 구경' : '🛍️ Market Tour: Taste seed hotteok, chat with vendor ladies, see Busan specialties',
          coordinates: { lat: 35.1007, lng: 129.0298 },
          travelTime: isKorean ? '지하철 25분' : '25 min by metro',
          transportInfo: isKorean ? '🚇 1호선 자갈치역' : '🚇 Jagalchi Station (Line 1)',
        },
        {
          name: isKorean ? '기장 대변항 (어촌 체험)' : 'Gijang Daebyeon Port (Fishing Village)',
          address: isKorean ? '기장군, 부산' : 'Gijang-gun, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '어촌 마을' : 'Fishing Village',
          description: isKorean ? '어부 아저씨들과 함께 멸치잡이 체험, 할매 손맛의 해물 라면을 맛보세요.' : 'Experience anchovy fishing with fishermen, taste grandma\'s seafood ramen.',
          dramaScene: isKorean ? '새벽 포구에서 어부들과 함께 일하며 바다 사람들의 삶을 배우는 장면' : 'Scenes learning fishermen\'s life working together at dawn port',
          regionalExperience: isKorean ? '🐟 어촌 체험: 멸치 덕장 구경, 할매 해물 라면, 어부들과 소주 한잔' : '🐟 Fishing Village: See anchovy drying racks, grandma\'s seafood ramen, soju with fishermen',
          coordinates: { lat: 35.2528, lng: 129.2245 },
          travelTime: isKorean ? '버스 50분' : '50 min by bus',
          transportInfo: isKorean ? '🚌 해운대에서 181번 버스' : '🚌 Bus 181 from Haeundae',
        },
      ],
      'game-food': [
        {
          name: isKorean ? 'BIFF 광장 (영화의 거리)' : 'BIFF Square (Movie Street)',
          address: isKorean ? '중구, 부산' : 'Jung-gu, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '길거리 음식' : 'Street Food',
          description: isKorean ? '부산의 명물 씨앗호떡과 길거리 음식의 성지. 영화제 분위기 속 먹거리 천국.' : 'Mecca of Busan\'s famous seed hotteok and street food. Food paradise with film festival vibes.',
          dramaScene: isKorean ? '붐비는 거리에서 호떡을 먹으며 게임 이야기를 나누는 장면' : 'Scenes eating hotteok and discussing games on crowded streets',
          regionalExperience: isKorean ? '🎬 먹자골목: 씨앗호떡, 야끼만두, 오징어튀김, 부산어묵' : '🎬 Food Alley: Seed hotteok, yaki mandu, fried squid, Busan fish cake',
          coordinates: { lat: 35.0986, lng: 129.0309 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 1호선 남포역' : '🚇 Nampo Station (Line 1)',
        },
        {
          name: isKorean ? '자갈치 시장' : 'Jagalchi Fish Market',
          address: isKorean ? '중구, 부산' : 'Jung-gu, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '해산물 시장' : 'Seafood Market',
          description: isKorean ? '한국 최대 수산시장. 1층에서 사서 2층에서 바로 먹는 짜릿한 경험.' : 'Korea\'s largest seafood market. Thrilling experience buying on 1st floor, eating on 2nd.',
          dramaScene: isKorean ? '시장 아지매들의 호객 소리와 활기찬 경매 장면' : 'Scenes of vendor ladies\' calls and lively auction atmosphere',
          regionalExperience: isKorean ? '🦞 해산물 투어: 싱싱한 회 맛보기, 해물찜, 소주 폭탄주' : '🦞 Seafood Tour: Fresh sashimi, seafood steam, soju bomb',
          coordinates: { lat: 35.0965, lng: 129.0306 },
          travelTime: isKorean ? '도보 5분' : '5 min walk',
          transportInfo: isKorean ? '🚶 BIFF광장에서 도보' : '🚶 Walk from BIFF Square',
        },
        {
          name: isKorean ? '해운대 포장마차 거리' : 'Haeundae Pojangmacha Street',
          address: isKorean ? '해운대구, 부산' : 'Haeundae-gu, Busan',
          region: isKorean ? '부산' : 'Busan',
          tag: isKorean ? '포장마차' : 'Street Stalls',
          description: isKorean ? '해변가 포장마차에서 바다를 보며 즐기는 야식과 게임.' : 'Late-night food and games enjoyed watching the sea at beach stalls.',
          dramaScene: isKorean ? '포장마차에서 술 한잔하며 달고나 게임을 하는 장면' : 'Scenes playing dalgona game while drinking at pojangmacha',
          regionalExperience: isKorean ? '🍻 야시장: 해운대 포차, 소주와 안주, 밤바다 산책' : '🍻 Night Market: Haeundae stalls, soju and snacks, night beach walk',
          coordinates: { lat: 35.1586, lng: 129.1603 },
          travelTime: isKorean ? '지하철 30분' : '30 min by metro',
          transportInfo: isKorean ? '🚇 2호선 해운대역' : '🚇 Haeundae Station (Line 2)',
        },
      ],
    },
    gyeonggi: {
      heartwarming: [
        {
          name: isKorean ? '수원 화성 행궁' : 'Suwon Hwaseong Haenggung Palace',
          address: isKorean ? '팔달구, 수원시, 경기도' : 'Paldal-gu, Suwon, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '역사 문화' : 'Historical Culture',
          description: isKorean ? '조선시대 궁궐에서 전통 문화 해설사와 함께 옛 이야기를 들으며 역사를 배워보세요.' : 'Learn history with traditional culture guides at Joseon palace, listening to old stories.',
          dramaScene: isKorean ? '궁궐 마당에서 지역 주민들과 함께하는 전통 문화 행사 장면' : 'Scenes of traditional cultural events with local residents in palace yard',
          regionalExperience: isKorean ? '🏰 전통 체험: 한복 입고 궁궐 산책, 전통 공예 배우기, 수원 화성 탐방' : '🏰 Traditional Experience: Palace walk in hanbok, learn traditional crafts, explore Hwaseong',
          coordinates: { lat: 37.2865, lng: 127.0161 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 1호선 수원역 → 🚌 버스' : '🚇 Suwon Station (Line 1) → 🚌 Bus',
        },
        {
          name: isKorean ? '양평 두물머리 농촌 마을' : 'Yangpyeong Dumulmeori Farm Village',
          address: isKorean ? '양서면, 양평군, 경기도' : 'Yangseo-myeon, Yangpyeong, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '농촌 체험' : 'Farm Experience',
          description: isKorean ? '서울 근교 농촌 마을에서 농부 할아버지와 함께 농사일을 도우며 시골의 정취를 느껴보세요.' : 'Help farming with grandpa farmer in rural village near Seoul, feel countryside atmosphere.',
          dramaScene: isKorean ? '논밭에서 땀 흘리며 일한 후 평상에서 막걸리를 나눠 마시는 장면' : 'Scenes sharing makgeolli on wooden platform after working hard in rice fields',
          regionalExperience: isKorean ? '🌾 농촌 체험: 텃밭 가꾸기, 농가 밥상, 할머니 손맛 김치' : '🌾 Farm Experience: Tend vegetable garden, farmhouse meal, grandma\'s homemade kimchi',
          coordinates: { lat: 37.5508, lng: 127.3284 },
          travelTime: isKorean ? '버스 60분' : '60 min by bus',
          transportInfo: isKorean ? '🚌 청량리에서 버스' : '🚌 Bus from Cheongnyangni',
        },
        {
          name: isKorean ? '가평 아침고요수목원 & 전원마을' : 'Gapyeong Morning Calm Garden & Country Village',
          address: isKorean ? '상면, 가평군, 경기도' : 'Sang-myeon, Gapyeong, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '자연 힐링' : 'Nature Healing',
          description: isKorean ? '아름다운 정원과 전원 마을에서 현지 주민들과 함께 자연 속 휴식을 즐기세요.' : 'Enjoy nature rest with local residents at beautiful garden and country village.',
          dramaScene: isKorean ? '정원을 거닐며 마을 어르신들과 인생 이야기를 나누는 장면' : 'Scenes walking through garden sharing life stories with village elders',
          regionalExperience: isKorean ? '🌸 전원 힐링: 수목원 산책, 마을 카페에서 차, 계절 꽃 감상' : '🌸 Country Healing: Garden walk, tea at village cafe, seasonal flowers',
          coordinates: { lat: 37.7443, lng: 127.3543 },
          travelTime: isKorean ? '차로 40분' : '40 min drive',
          transportInfo: isKorean ? '🚌 가평역에서 버스' : '🚌 Bus from Gapyeong Station',
        },
      ],
      'game-food': [
        {
          name: isKorean ? '대부도 (오징어게임 촬영지)' : 'Daebudo Island (Squid Game Filming Location)',
          address: isKorean ? '단원구, 안산시, 경기도' : 'Danwon-gu, Ansan, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '실제 촬영지' : 'Actual Filming Site',
          description: isKorean ? '오징어게임의 야외 게임 장면들이 촬영된 바로 그 섬! 실제 촬영지를 걸어보세요.' : 'The actual island where Squid Game outdoor scenes were filmed! Walk the real filming locations.',
          dramaScene: isKorean ? '게임 참가자들이 섬에 도착하는 장면, 야외 게임 시퀀스가 펼쳐진 곳' : 'Scenes of players arriving at island, where outdoor game sequences took place',
          regionalExperience: isKorean ? '🎮 촬영지 투어: 실제 게임 장소 방문, 포토존, 드라마 팬들과 교류' : '🎮 Filming Site Tour: Visit actual game locations, photo zones, meet drama fans',
          coordinates: { lat: 37.1877, lng: 126.5826 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚌 서울에서 버스 90분' : '🚌 90 min bus from Seoul',
        },
        {
          name: isKorean ? '일산 호수공원 & 라페스타' : 'Ilsan Lake Park & LaFesta',
          address: isKorean ? '일산동구, 고양시, 경기도' : 'Ilsandong-gu, Goyang, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '먹거리 거리' : 'Food Street',
          description: isKorean ? '쇼핑몰과 먹거리 거리가 모인 복합 공간. 야외 게임과 길거리 음식을 즐겨보세요.' : 'Complex space with shopping mall and food street. Enjoy outdoor games and street food.',
          dramaScene: isKorean ? '쇼핑몰에서 게임 아케이드를 즐기고 먹거리 거리를 누비는 장면' : 'Scenes enjoying game arcade at mall and wandering food street',
          regionalExperience: isKorean ? '🎪 복합몰: 보드게임 카페, 먹거리 투어, 야외 공연' : '🎪 Complex Mall: Board game cafe, food tour, outdoor performances',
          coordinates: { lat: 37.6566, lng: 126.7729 },
          travelTime: isKorean ? '지하철 50분' : '50 min by metro',
          transportInfo: isKorean ? '🚇 3호선 정발산역' : '🚇 Jeongbalsan Station (Line 3)',
        },
        {
          name: isKorean ? '수원 통닭거리' : 'Suwon Fried Chicken Street',
          address: isKorean ? '팔달구, 수원시, 경기도' : 'Paldal-gu, Suwon, Gyeonggi',
          region: isKorean ? '경기도' : 'Gyeonggi',
          tag: isKorean ? '치킨 맛집' : 'Chicken Restaurants',
          description: isKorean ? '수원 왕갈비통닭으로 유명한 치킨 거리. 게임하며 치킨 먹기 좋은 포장마차들.' : 'Famous chicken street known for Suwon Wang Galbi chicken. Great stalls for eating chicken while gaming.',
          dramaScene: isKorean ? '치킨집에서 소주와 치킨을 먹으며 카드게임을 하는 장면' : 'Scenes playing card games while eating soju and chicken at chicken restaurant',
          regionalExperience: isKorean ? '🍗 치킨 투어: 왕갈비통닭, 소주 폭탄주, 포장마차 게임' : '🍗 Chicken Tour: Wang Galbi chicken, soju bomb, pojangmacha games',
          coordinates: { lat: 37.2794, lng: 127.0108 },
          travelTime: isKorean ? '지하철 15분' : '15 min by metro',
          transportInfo: isKorean ? '🚇 1호선 수원역' : '🚇 Suwon Station (Line 1)',
        },
      ],
    },
    gangwon: {
      heartwarming: [
        {
          name: isKorean ? '정선 아리랑시장' : 'Jeongseon Arirang Market',
          address: isKorean ? '정선읍, 정선군, 강원도' : 'Jeongseon-eup, Jeongseon, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '전통 5일장' : 'Traditional 5-Day Market',
          description: isKorean ? '산골 마을의 5일장. 할머니들이 직접 기른 산나물과 농산물을 파는 정겨운 시장.' : 'Mountain village 5-day market. Heartwarming market where grandmas sell their own mountain vegetables and produce.',
          dramaScene: isKorean ? '장날 할머니들과 정담게 흥정하며 농산물을 사는 인정 넘치는 장면' : 'Heartwarming scenes bargaining warmly with grandmas on market day',
          regionalExperience: isKorean ? '🥬 전통 장터: 산나물 구경, 할머니 손맛 부침개, 막걸리 한잔' : '🥬 Traditional Market: See mountain vegetables, grandma\'s pancakes, glass of makgeolli',
          coordinates: { lat: 37.3806, lng: 128.6659 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚌 서울에서 버스 3시간' : '🚌 3 hours bus from Seoul',
        },
        {
          name: isKorean ? '평창 양떼목장 & 목동 가족' : 'Pyeongchang Sheep Ranch & Shepherd Family',
          address: isKorean ? '대관령면, 평창군, 강원도' : 'Daegwallyeong-myeon, Pyeongchang, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '목장 체험' : 'Ranch Experience',
          description: isKorean ? '목동 가족과 함께 양떼를 돌보며 고산 지대 생활의 순수함을 느껴보세요.' : 'Care for sheep with shepherd family, feel the purity of highland life.',
          dramaScene: isKorean ? '푸른 초원에서 양떼와 뛰어놀며 목동 가족과 점심을 나눠먹는 장면' : 'Scenes playing with sheep on green meadows and sharing lunch with shepherd family',
          regionalExperience: isKorean ? '🐑 목장 힐링: 양 먹이주기, 목동 가족 밥상, 초원 산책' : '🐑 Ranch Healing: Feed sheep, shepherd family meal, meadow walk',
          coordinates: { lat: 37.6750, lng: 128.7189 },
          travelTime: isKorean ? '차로 50분' : '50 min drive',
          transportInfo: isKorean ? '🚗 정선에서 대관령 방향' : '🚗 Toward Daegwallyeong from Jeongseon',
        },
        {
          name: isKorean ? '강릉 주문진 어촌계 & 어촌체험' : 'Gangneung Jumunjin Fishing Community',
          address: isKorean ? '주문진읍, 강릉시, 강원도' : 'Jumunjin-eup, Gangneung, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '어촌 마을' : 'Fishing Village',
          description: isKorean ? '동해 바다 어부들과 함께 배를 타고 나가 직접 잡은 생선으로 회를 떠보세요.' : 'Go out on boat with East Sea fishermen, make sashimi from fish you caught.',
          dramaScene: isKorean ? '어부들과 함께 배에서 그물을 당기며 바다의 삶을 배우는 장면' : 'Scenes learning sea life pulling nets with fishermen on boat',
          regionalExperience: isKorean ? '⛵ 어촌 체험: 어부 할아버지와 출항, 싱싱한 회, 바닷가 마을 산책' : '⛵ Fishing Experience: Depart with fisherman grandpa, fresh sashimi, seaside village walk',
          coordinates: { lat: 37.8946, lng: 128.8188 },
          travelTime: isKorean ? '차로 90분' : '90 min drive',
          transportInfo: isKorean ? '🚌 정선에서 동해안 방향' : '🚌 Toward east coast from Jeongseon',
        },
      ],
      'game-food': [
        {
          name: isKorean ? '춘천 닭갈비 골목' : 'Chuncheon Dakgalbi Alley',
          address: isKorean ? '중앙로, 춘천시, 강원도' : 'Jungang-ro, Chuncheon, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '맛집 골목' : 'Restaurant Alley',
          description: isKorean ? '춘천의 명물 닭갈비를 먹으며 즐기는 게임과 소주. 철판 닭갈비의 성지.' : 'Games and soju while eating Chuncheon\'s famous dakgalbi. Holy land of iron plate dakgalbi.',
          dramaScene: isKorean ? '철판 닭갈비를 둘러싸고 게임을 하며 술을 마시는 활기찬 장면' : 'Lively scenes playing games and drinking around iron plate dakgalbi',
          regionalExperience: isKorean ? '🍖 닭갈비 투어: 철판 닭갈비, 막국수, 소주 폭탄주' : '🍖 Dakgalbi Tour: Iron plate dakgalbi, makguksu, soju bomb',
          coordinates: { lat: 37.8813, lng: 127.7300 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚂 ITX 춘천역' : '🚂 ITX Chuncheon Station',
        },
        {
          name: isKorean ? '속초 중앙시장 & 아바이마을' : 'Sokcho Jungang Market & Abai Village',
          address: isKorean ? '중앙로, 속초시, 강원도' : 'Jungang-ro, Sokcho, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '해산물 시장' : 'Seafood Market',
          description: isKorean ? '속초의 유명 먹거리 시장. 닭강정, 아바이순대, 오징어순대를 맛보세요.' : 'Sokcho\'s famous food market. Taste dakgangjeong, abai sundae, squid sundae.',
          dramaScene: isKorean ? '시장 골목을 누비며 길거리 음식을 먹고 배를 타고 건너가는 장면' : 'Scenes wandering market alleys eating street food and crossing by boat',
          regionalExperience: isKorean ? '🦑 속초 먹방: 닭강정, 오징어순대, 아바이순대, 갯배 타기' : '🦑 Sokcho Mukbang: Dakgangjeong, squid sundae, abai sundae, cable ferry ride',
          coordinates: { lat: 38.2070, lng: 128.5918 },
          travelTime: isKorean ? '버스 90분' : '90 min by bus',
          transportInfo: isKorean ? '🚌 춘천에서 속초 방향' : '🚌 Toward Sokcho from Chuncheon',
        },
        {
          name: isKorean ? '강릉 중앙시장 & 포장마차' : 'Gangneung Jungang Market & Pojangmacha',
          address: isKorean ? '금성로, 강릉시, 강원도' : 'Geumseong-ro, Gangneung, Gangwon',
          region: isKorean ? '강원도' : 'Gangwon',
          tag: isKorean ? '야시장' : 'Night Market',
          description: isKorean ? '강릉의 야시장과 포장마차 거리. 오징어, 한치를 구워먹으며 게임을 즐겨보세요.' : 'Gangneung\'s night market and pojangmacha street. Enjoy games while eating grilled squid and hanchi.',
          dramaScene: isKorean ? '포장마차에서 오징어를 굽고 소주를 마시며 달고나 게임을 하는 장면' : 'Scenes grilling squid, drinking soju and playing dalgona game at pojangmacha',
          regionalExperience: isKorean ? '🍻 야시장: 오징어구이, 한치물회, 소주와 게임' : '🍻 Night Market: Grilled squid, hanchi mulhoe, soju and games',
          coordinates: { lat: 37.7519, lng: 128.8761 },
          travelTime: isKorean ? '버스 40분' : '40 min by bus',
          transportInfo: isKorean ? '🚌 속초에서 강릉 방향' : '🚌 Toward Gangneung from Sokcho',
        },
      ],
    },
    gyeongsang: {
      heartwarming: [
        {
          name: isKorean ? '안동 하회마을' : 'Andong Hahoe Village',
          address: isKorean ? '풍천면, 안동시, 경상북도' : 'Pungcheon-myeon, Andong, Gyeongsangbuk-do',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '전통 마을' : 'Traditional Village',
          description: isKorean ? '600년 역사의 양반 마을. 고택에서 하룻밤 묵으며 종가 음식과 예절을 배워보세요.' : '600-year-old yangban village. Stay overnight in old house, learn jonggaa food and etiquette.',
          dramaScene: isKorean ? '고택 마루에 앉아 어르신들께 옛날 이야기를 듣는 장면' : 'Scenes sitting on old house porch listening to elders\' old stories',
          regionalExperience: isKorean ? '🏛️ 고택 체험: 종가집 스테이, 전통 차례상, 하회탈춤 관람' : '🏛️ Old House Experience: Jonggaa house stay, traditional ancestral table, Hahoe mask dance',
          coordinates: { lat: 36.5391, lng: 128.5185 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚌 서울에서 버스 3.5시간' : '🚌 3.5 hours bus from Seoul',
        },
        {
          name: isKorean ? '경주 교촌마을 한옥 체험' : 'Gyeongju Gyochon Village Hanok Stay',
          address: isKorean ? '교동, 경주시, 경상북도' : 'Gyo-dong, Gyeongju, Gyeongsangbuk-do',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '한옥 스테이' : 'Hanok Stay',
          description: isKorean ? '신라 천년 고도의 한옥 마을. 최 부자댁에서 경주 빵과 교동 법주를 맛보세요.' : 'Hanok village in Silla\'s thousand-year capital. Taste Gyeongju bread and Gyodong beopju at Choi rich house.',
          dramaScene: isKorean ? '한옥 마당에서 주인 할머니와 차를 마시며 가문의 역사를 듣는 장면' : 'Scenes drinking tea with host grandma in hanok yard, hearing family history',
          regionalExperience: isKorean ? '🏠 경주 체험: 한옥 스테이, 최 부자댁 방문, 교동 법주 시음' : '🏠 Gyeongju Experience: Hanok stay, visit Choi rich house, taste Gyodong beopju',
          coordinates: { lat: 35.8356, lng: 129.2143 },
          travelTime: isKorean ? '버스 60분' : '60 min by bus',
          transportInfo: isKorean ? '🚌 안동에서 경주 방향' : '🚌 Toward Gyeongju from Andong',
        },
        {
          name: isKorean ? '통영 동피랑 벽화마을' : 'Tongyeong Dongpirang Mural Village',
          address: isKorean ? '동호동, 통영시, 경상남도' : 'Dongho-dong, Tongyeong, Gyeongsangnam-do',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '항구 마을' : 'Port Village',
          description: isKorean ? '바다가 보이는 언덕 마을. 주민들과 함께 벽화를 그리고 바다 이야기를 들어보세요.' : 'Hill village overlooking the sea. Paint murals with residents and hear sea stories.',
          dramaScene: isKorean ? '골목길에서 마을 할머니들과 나물을 다듬으며 이야기를 나누는 장면' : 'Scenes trimming vegetables and chatting with village grandmas in alleys',
          regionalExperience: isKorean ? '🎨 항구 체험: 벽화 골목 산책, 주민 카페, 통영 꿀빵' : '🎨 Port Experience: Mural alley walk, resident cafe, Tongyeong honey bread',
          coordinates: { lat: 34.8440, lng: 128.4331 },
          travelTime: isKorean ? '버스 120분' : '120 min by bus',
          transportInfo: isKorean ? '🚌 경주에서 통영 방향' : '🚌 Toward Tongyeong from Gyeongju',
        },
      ],
      'game-food': [
        {
          name: isKorean ? '대구 서문시장' : 'Daegu Seomun Market',
          address: isKorean ? '큰장로, 대구' : 'Keunjang-ro, Daegu',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '전통 시장' : 'Traditional Market',
          description: isKorean ? '대구의 명물 납작만두와 막창 골목. 게임하며 먹기 좋은 야시장.' : 'Daegu\'s famous flat mandu and makchang alley. Great night market for gaming and eating.',
          dramaScene: isKorean ? '시장 골목에서 납작만두를 먹으며 게임 이야기를 나누는 장면' : 'Scenes eating flat mandu and discussing games in market alley',
          regionalExperience: isKorean ? '🥟 대구 먹방: 납작만두, 막창, 소주, 야시장 게임' : '🥟 Daegu Mukbang: Flat mandu, makchang, soju, night market games',
          coordinates: { lat: 35.8714, lng: 128.5852 },
          travelTime: isKorean ? '여기서 시작' : 'Start here',
          transportInfo: isKorean ? '🚇 대구 지하철 서문시장역' : '🚇 Daegu Metro Seomun Market Station',
        },
        {
          name: isKorean ? '포항 죽도시장' : 'Pohang Jukdo Market',
          address: isKorean ? '죽도동, 포항시, 경상북도' : 'Jukdo-dong, Pohang, Gyeongsangbuk-do',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '해산물 시장' : 'Seafood Market',
          description: isKorean ? '포항의 활어 시장. 싱싱한 대게와 과메기를 먹으며 달고나 게임을 즐겨보세요.' : 'Pohang\'s live fish market. Enjoy dalgona game while eating fresh snow crab and gwamegi.',
          dramaScene: isKorean ? '횟집에서 대게를 까먹으며 소주와 게임을 즐기는 장면' : 'Scenes cracking snow crab and enjoying soju and games at raw fish restaurant',
          regionalExperience: isKorean ? '🦀 포항 먹방: 대게, 과메기, 물회, 소주 폭탄주' : '🦀 Pohang Mukbang: Snow crab, gwamegi, mulhoe, soju bomb',
          coordinates: { lat: 36.0326, lng: 129.3656 },
          travelTime: isKorean ? '버스 60분' : '60 min by bus',
          transportInfo: isKorean ? '🚌 대구에서 포항 방향' : '🚌 Toward Pohang from Daegu',
        },
        {
          name: isKorean ? '진주 중앙시장 & 포장마차' : 'Jinju Jungang Market & Pojangmacha',
          address: isKorean ? '중앙로, 진주시, 경상남도' : 'Jungang-ro, Jinju, Gyeongsangnam-do',
          region: isKorean ? '경상도' : 'Gyeongsang',
          tag: isKorean ? '야시장' : 'Night Market',
          description: isKorean ? '진주의 명물 비빔밥과 육회를 먹으며 포장마차에서 게임을 즐겨보세요.' : 'Enjoy games at pojangmacha while eating Jinju\'s famous bibimbap and yukhoe.',
          dramaScene: isKorean ? '포장마차에서 진주 비빔밥을 먹으며 카드게임을 하는 장면' : 'Scenes playing card games while eating Jinju bibimbap at pojangmacha',
          regionalExperience: isKorean ? '🍲 진주 먹방: 진주비빔밥, 육회, 소주와 게임' : '🍲 Jinju Mukbang: Jinju bibimbap, yukhoe, soju and games',
          coordinates: { lat: 35.1797, lng: 128.1076 },
          travelTime: isKorean ? '버스 90분' : '90 min by bus',
          transportInfo: isKorean ? '🚌 포항에서 진주 방향' : '🚌 Toward Jinju from Pohang',
        },
      ],
    },
  };

  return data[region]?.[dramaTheme] || data.seoul[dramaTheme];
}
